[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.css" # css files too
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.json"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.gif"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.ttf"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.map"
  [headers.values]
    Cache-Control = "public, max-age=604800"
